#!/bin/bash

mysql -u$FIELDSMAN_TEST_DB_USER -p$FIELDSMAN_TEST_DB_PASSWORD -h$FIELDSMAN_TEST_DB_HOST <<EOF
CREATE DATABASE IF NOT EXISTS fieldsman_test;
USE fieldsman_test;

CREATE TABLE IF NOT EXISTS payloads (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    content TEXT
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS fields (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

EOF
